const cursos = [ { id: "intro_admin", nombre: "Introducción a la administración", ciclo: 1, creditos: 3 }, { id: "fund_conta", nombre: "Fundamentos de contabilidad y finanzas", ciclo: 1, creditos: 4 }, { id: "mate1", nombre: "Matemática para los negocios 1", ciclo: 1, creditos: 3 }, { id: "textos1", nombre: "Comprensión y Redacción de Textos 1", ciclo: 1, creditos: 4 }, { id: "peru_actual", nombre: "Problemas y desafíos en el Perú actual", ciclo: 1, creditos: 3 }, { id: "vida_universitaria", nombre: "Introducción a la vida universitaria", ciclo: 1, creditos: 2 },

{ id: "gestion_general", nombre: "Gestión General", ciclo: 2, creditos: 4, prereq: ["intro_admin"] }, { id: "mate2", nombre: "Matemática para los negocios 2", ciclo: 2, creditos: 4, prereq: ["mate1"] }, { id: "ingles1", nombre: "Inglés 1", ciclo: 2, creditos: 3 }, { id: "textos2", nombre: "Comprensión y Redacción de Textos 2", ciclo: 2, creditos: 4, prereq: ["textos1"] }, { id: "conta_financiera", nombre: "Contabilidad financiera", ciclo: 2, creditos: 2, prereq: ["fund_conta"] }, { id: "derecho_empresarial", nombre: "Derecho Empresarial", ciclo: 2, creditos: 3 },

{ id: "estadistica", nombre: "Estadística aplicada para los negocios", ciclo: 3, creditos: 4, prereq: ["mate2"] }, { id: "informatica", nombre: "Informática para los negocios", ciclo: 3, creditos: 5 }, { id: "ingles2", nombre: "Inglés 2", ciclo: 3, creditos: 3, prereq: ["ingles1"] }, { id: "ambiente", nombre: "Individuo y medio ambiente", ciclo: 3, creditos: 2 }, { id: "conta_gerencial", nombre: "Contabilidad gerencial y de costos", ciclo: 3, creditos: 5, prereq: ["conta_financiera"] },

{ id: "comportamiento", nombre: "Comportamiento y cultura en las organizaciones", ciclo: 4, creditos: 5, prereq: ["intro_admin"] }, { id: "microeconomia", nombre: "Microeconomía y Microeconomía", ciclo: 4, creditos: 3, prereq: ["gestion_general"] }, { id: "finanzas_aplicadas", nombre: "Finanzas aplicadas", ciclo: 4, creditos: 4, prereq: ["conta_gerencial"] }, { id: "etica", nombre: "Ciudadanía y reflexión ética", ciclo: 4, creditos: 3, prereq: ["textos1"] }, { id: "ingles3", nombre: "Inglés 3", ciclo: 4, creditos: 3, prereq: ["ingles2"] }, { id: "marketing", nombre: "Fundamentos de marketing", ciclo: 4, creditos: 3, prereq: ["gestion_general"] },

{ id: "integrador1", nombre: "Curso integrador en administración y negocios", ciclo: 5, creditos: 5, prereq: ["microeconomia", "estadistica", "finanzas_aplicadas", "marketing", "informatica"] }, { id: "investigacion_academica", nombre: "Investigación académica", ciclo: 5, creditos: 4, prereq: ["ambiente", "textos1"] }, { id: "investigacion_mercados", nombre: "Investigación de mercados", ciclo: 5, creditos: 5, prereq: ["marketing"] }, { id: "ingles4", nombre: "Inglés 4", ciclo: 5, creditos: 3, prereq: ["ingles3"] }, { id: "investigacion_operativa", nombre: "Investigación Operativa", ciclo: 5, creditos: 5, prereq: ["estadistica"] },

{ id: "ventas", nombre: "Gestión de ventas", ciclo: 6, creditos: 3, prereq: ["investigacion_mercados"] }, { id: "negocios_digitales", nombre: "Negocios digitales", ciclo: 6, creditos: 3, prereq: ["marketing", "informatica"] }, { id: "innovacion", nombre: "Innovación y transformación empresarial", ciclo: 6, creditos: 3, prereq: ["integrador1"] }, { id: "habilidades_gerenciales", nombre: "Taller de habilidades gerenciales", ciclo: 6, creditos: 4, prereq: ["finanzas_aplicadas"] }, { id: "talento_humano", nombre: "Gestión de talento humano", ciclo: 6, creditos: 4, prereq: ["comportamiento"] }, { id: "evaluacion_financiera", nombre: "Gerencia de evaluación financiera", ciclo: 6, creditos: 3, prereq: ["comportamiento"] },

{ id: "operaciones", nombre: "Administración de operaciones", ciclo: 7, creditos: 5, prereq: ["investigacion_operativa"] }, { id: "estrategias_accion", nombre: "Planificación y estrategias de acción", ciclo: 7, creditos: 5, prereq: ["investigacion_operativa"] }, { id: "diseno_org", nombre: "Diseño organizacional", ciclo: 7, creditos: 3, prereq: ["evaluacion_financiera"] }, { id: "presupuestal", nombre: "Formulación y evaluación presupuestal", ciclo: 7, creditos: 4, prereq: ["evaluacion_financiera"] }, { id: "creatividad", nombre: "Creatividad empresarial", ciclo: 7, creditos: 3 }, { id: "business_english", nombre: "Elementary business english", ciclo: 7, creditos: 4, prereq: ["ingles4"] }, { id: "logistica", nombre: "Gerencia de servicios logísticos", ciclo: 7, creditos: 3 },

{ id: "suministro", nombre: "Gestión y suministro de bienes y servicios", ciclo: 8, creditos: 4, prereq: ["operaciones"] }, { id: "analitica", nombre: "Analítica de datos", ciclo: 8, creditos: 4, prereq: ["investigacion_mercados"] }, { id: "formacion_investigacion", nombre: "Formación para la investigación - administración y negocios", ciclo: 8, creditos: 4, prereq: ["integrador1"] }, { id: "empleabilidad", nombre: "Formación para la empleabilidad", ciclo: 8, creditos: 3, prereq: ["integrador1"] }, { id: "direccion_personas", nombre: "Dirección de personas", ciclo: 8, creditos: 5, prereq: ["talento_humano"] },

{ id: "integrador2", nombre: "Curso integrador en gestión estratégica de empresas", ciclo: 9, creditos: 4, prereq: ["integrador1", "presupuestal"] }, { id: "etica_prof", nombre: "Ética profesional y responsabilidad social", ciclo: 9, creditos: 3, prereq: ["comportamiento"] }, { id: "direccion_comercial", nombre: "Dirección comercial", ciclo: 9, creditos: 5, prereq: ["ventas"] }, { id: "negociacion", nombre: "Negociación y toma de decisiones", ciclo: 9, creditos: 5, prereq: ["diseno_org"] }, { id: "community", nombre: "Community manager", ciclo: 9, creditos: 3 },

{ id: "desarrollo_prof", nombre: "Herramientas de desarrollo profesional - gestión", ciclo: 10, creditos: 4, prereq: ["integrador1"] }, { id: "direccion_financiera", nombre: "Dirección financiera", ciclo: 10, creditos: 4, prereq: ["presupuestal"] }, { id: "taller_investigacion", nombre: "Taller de investigación - administración de empresas", ciclo: 10, creditos: 4, prereq: ["formacion_investigacion"] }, { id: "direccion_estrategica", nombre: "Dirección estratégica", ciclo: 10, creditos: 5, prereq: ["estrategias_accion"] }, { id: "branding", nombre: "Branding", ciclo: 10, creditos: 3 }, { id: "liderazgo", nombre: "Liderazgo y conformación de equipos", ciclo: 10, creditos: 3 }, ];

const container = document.getElementById("cursos");

cursos.forEach(curso => { const div = document.createElement("div"); div.className = "curso"; div.dataset.id = curso.id; if (curso.prereq) div.dataset.prereq = curso.prereq.join(',');

const checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.id = curso.id; checkbox.disabled = !!curso.prereq; checkbox.addEventListener("change", (e) => { if (!e.target.checked) return; document.querySelectorAll('[data-prereq]').forEach(el => { const prereqs = el.dataset.prereq.split(','); if (prereqs.every(p => document.getElementById(p).checked)) { document.getElementById(el.dataset.id).disabled = false; } }); });

const label = document.createElement("label"); label.htmlFor = curso.id; label.innerText = ${curso.nombre} (${curso.creditos} cr);

div.appendChild(checkbox); div.appendChild(label); container.appendChild(div); });

